## 01.LINUX Ubuntu作業系統與指令簡介

## 02. PYTHON資料庫CRUD-SQL&NoSQL

## 03. PYTHON正則表達式 - Regular Expression

#### 引用套件

In [1]:
import re

<img src="./data/pic1.png" width = "400" height = "300" alt="图片名称" align=center />
<img src="./data/pic2.png" width = "400" height = "300" alt="图片名称" align=center />

##### re.split 函数

In [16]:
import re
ex1 = 'A b C 1 2 3'
print(re.split('[\d]',ex1))  # \d 數字
print(re.split('[\D]',ex1)) # \D 非數字

['A b C ', ' ', ' ', '']
['', '', '', '', '', '', '1', '2', '3']


In [17]:
import re
ex1 = 'A b C 1 2 3'
print(re.split('[\s]',ex1))# \s 空白字元 
print(re.split('[\S]',ex1)) # \S 非空白字元 

['A', 'b', 'C', '1', '2', '3']
['', ' ', ' ', ' ', ' ', ' ', '']


In [18]:
import re
ex1 = 'A b 1 _ ? +'
print(re.split('[\w]',ex1)) # \w 數字, 大小寫字母, 底線
print(re.split('[\W]',ex1)) # \W 非數字, 大小寫字母, 底線

['', ' ', ' ', ' ', ' ? +']
['A', 'b', '1', '_', '', '', '', '']


In [21]:
import re
ex1 = 'aaazbbbccca'
print(re.split('[a-b]*',ex1)) # * 比對前一個字元0次或多次
print(re.split('[b-c]+',ex1)) # + 比對前一個字元1次或多次
print(re.split('[a]?',ex1)) # ? 比對前一個字元0次或1次

['', 'z', 'ccc', '']
['aaaz', 'a']
['', '', '', 'zbbbccc', '']


c:\users\lifeplus\appdata\local\programs\python\python35\lib\re.py:203: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


##### re.finall函數

說明 : 找到 RE 匹配的所有子串，並把它們作為一個列表返回

In [22]:
import re
re.findall('[a-z]{3}','a bb ccc dddd eeeee fffff') #印出滿足a-z , 其中連續3個一樣的字

['ccc', 'ddd', 'eee', 'fff']

In [24]:
import re
re.findall('[a-z]{3,}','a bb ccc dddd eeeee fffff') #印出滿足a-z , 其中連續3個或以上一樣的字

['ccc', 'dddd', 'eeeee', 'fffff']

In [25]:
import re
re.findall('[a-z]{3,4}','a bb ccc dddd eeeee fffff') #印出滿足a-z , 其中連續3-4個一樣的字

['ccc', 'dddd', 'eeee', 'ffff']

In [27]:
import re
re.findall('[a-z]{,4}','a bb ccc dddd eeeee fffff') #印出滿足a-z , 其中連續4個或以下一樣的字

['a', '', 'bb', '', 'ccc', '', 'dddd', '', 'eeee', 'e', '', 'ffff', 'f', '']

In [28]:
import re
re.findall('[a-z]{,4}','abbcccddddeeeeefffff') #印出滿足a-z , 其中連續4個或以下一樣的字

['abbc', 'ccdd', 'ddee', 'eeef', 'ffff', '']

Email 正則表示法

<img src="./data/pic3.png" width = "700" height = "600" alt="图片名称" align=center />

In [32]:
import re
mail = '123@gmail.com abc123@yahoo.com.tw 5678_abc@pchome.com.tw asdaa'

re.findall(r'([a-zA-Z0-9_]+@[a-zA-Z0-9\.]+)',mail)


['123@gmail.com', 'abc123@yahoo.com.tw', '5678_abc@pchome.com.tw']

In [33]:
re.findall(r'([a-zA-Z0-9_]@[a-zA-Z0-9\.])',mail)


['3@g', '3@y', 'c@p']

In [34]:
re.findall(r'([a-zA-Z0-9_]+@[a-zA-Z0-9\._]+)',mail)


['123@gmail.com', 'abc123@yahoo.com.tw', '5678_abc@pchome.com.tw']

In [36]:
import re
phone = "(04) 513-1238,0932 333-222,(0932)-333 222"

re.findall(r'\(?\d{4}\)?[\s\-]\d{3}[\-\s]\d{3}',phone)

['0932 333-222', '(0932)-333 222']

* greedy : 代表所有可能的匹配結果中，取字元數最多的。 *、+都是
* non-greedy : 代表所有可能的匹配結果中，取字元數最少的*?、+?都是

In [39]:
import re

z = 'prevx1234x'
print(re.findall('pre(.+)x',z))
print(re.findall('pre(.+?)x',z))
print(re.findall('pre(.+)?x',z))

['vx1234']
['v']
['vx1234']


In [45]:
import re
a = '<title>TestA</title>'
print(re.findall('<.+>',a))
print(re.findall('<.+?>',a))
print(re.split('<.+?>',a))

['<title>TestA</title>']
['<title>', '</title>']
['', 'TestA', '']


##### re.match函数

re.match(pattern,string,flags=0)

In [2]:
print(re.match('www','www.google.com.tw').span())

(0, 3)


In [3]:
print(re.match('google','www.google.com.tw'))

None


##### re.search 搜尋函數

說明: 決定 RE 是否在字符串剛開始的位置匹配

re.search(pattern, string, flags=0)



##### re.sub 替換函數

re.sub(pattern, repl, string, count=0, flags=0)

## 04. PYTHON JSON

#### 引用套件

In [5]:
import json

* EnCode : json.dumps()
* DeCode : json.loads()

#### Pytohn data structure to Json


In [6]:
import json

data = {
    'no' : 1,
    'name' : "google",
    'url' : 'http://www.google.com.tw'
}

json_str = json.dumps(data)

In [7]:
repr(data)

"{'name': 'google', 'url': 'http://www.google.com.tw', 'no': 1}"

In [8]:
json_str

'{"name": "google", "url": "http://www.google.com.tw", "no": 1}'

#### Json to Python data structure

In [9]:
data2 = json.loads(json_str)
data2

{'name': 'google', 'no': 1, 'url': 'http://www.google.com.tw'}

In [10]:
data2['name']

'google'

## 05. PYTHON資料分析與視覺化繪圖 I - Numpy 

NumPy，全名為 Numerical Python 創建一種稱為 ndarray 的型別，彌補了原生 list 缺少的元素級別（element-wise）運算功能 主要用於資料處理上。Numpy 底層以 C 和 Fortran 語言實作，能快速操作多重維度的陣列

#### 安裝套件

* Python 2+ : pip install numpy
* Python 3+ : pip3 install numpy

#### 引用套件

In [14]:
import numpy as np

In [ ]:
pip3 install numpy

#### 初始化陣列

##### 使用Python 列表建立陣列

In [17]:
np.array([1,3,5])  #  [1 3 5]
np.array([[1,2,],[3,4],[5,6]])  # [[1 2] [3 4] [5 6]]

array([[1, 2],
       [3, 4],
       [5, 6]])

##### 使用Numpy arange函數建立連續數值陣列

In [19]:
np.arange(1,10)  # [1 2 3 4 5 6 7 8 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 使用Numpy linspace函數建立連續等距數值陣列

In [21]:
np.linspace(0,4,11) # [0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4. ]

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ])

##### 建立填滿 0 的陣列

In [22]:
np.zeros([2, 3]) # [[0. 0. 0.] [0. 0. 0.]]

array([[0., 0., 0.],
       [0., 0., 0.]])

##### 建立填滿 1 的陣列

In [23]:
np.ones([2, 3]) #[[1. 1. 1.] [1. 1. 1.]]

array([[1., 1., 1.],
       [1., 1., 1.]])

##### 建立對角線為1的對角矩陣陣列

In [24]:
np.eye(10) 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##### 建立隨機數值陣列

In [31]:
#rand : 给定維度生成[0,1]之間的數值陣列，包含0，不包含1
print(np.random.rand(5)) # [0.15385879, 0.64608619, 0.72079961, 0.3115263 , 0.6021007 ]
print("-----")
print(np.random.rand(4,2))
print("-----")
print(np.random.rand(4,3,2))

[0.55734639 0.03520794 0.99175963 0.5654693  0.16516575]
-----
[[0.34328597 0.62637326]
 [0.78626113 0.84233587]
 [0.23833381 0.12867231]
 [0.83740742 0.79276578]]
-----
[[[0.81410014 0.95695662]
  [0.90306447 0.2204284 ]
  [0.16638669 0.29427577]]

 [[0.35827674 0.9788805 ]
  [0.37734338 0.41260329]
  [0.17525079 0.78106372]]

 [[0.71445866 0.44687649]
  [0.23835909 0.79108528]
  [0.61194148 0.62393862]]

 [[0.40060584 0.85114819]
  [0.87322561 0.05759597]
  [0.79649759 0.29947476]]]


In [32]:
#randn : 给定維度生成常態分佈的數值陣列 , N（0,1）
print(np.random.randn(5))
print("-----")
print(np.random.randn(4,2))
print("-----")
print(np.random.randn(4,3,2))


[-0.06824035 -1.7322277  -0.98503595  0.06538166 -0.67853225]
-----
[[-0.07809758 -0.0152411 ]
 [-0.1079803   0.1569482 ]
 [ 1.43731852  0.83310644]
 [ 1.00216484 -1.01469143]]
-----
[[[-2.08188357  1.50470241]
  [ 1.87064354 -0.74351578]
  [ 0.80728859 -0.01722511]]

 [[ 0.92801297 -0.63040288]
  [-0.98335235 -0.12539732]
  [-0.77670728 -0.1011454 ]]

 [[-0.55669677  1.28375569]
  [ 0.80147358  0.27938645]
  [ 0.17311571  1.31685716]]

 [[-0.29208555  0.5282701 ]
  [ 1.2024841   3.11181381]
  [-0.76753056 -0.61432541]]]


In [34]:
#randint : 给定維度生成隨機整數數值陣列 
print(np.random.randint(6,size=5))
print("-----")
print(np.random.randint(2,10))
print("-----")
print(np.random.randint(-10,10,size=(2,2)))

[3 3 3 4 1]
-----
8
-----
[[9 5]
 [2 9]]


In [35]:
#從给定的一维陣列中生成随數值
demo_list = [10,20,30,40,50]
#demo_list = ['Acer', 'ASUS','DELL','HP', 'APPLE']
np.random.choice(demo_list,size=(2,5), p=[0.1,0.6,0.1,0.1,0.1])

array([[40, 20, 20, 20, 20],
       [20, 20, 50, 20, 20]])

In [40]:
#  從檔CSV案讀取資料
a = np.genfromtxt('data/NPdata.csv', delimiter=',')
print(a)

[[ 1. 10. 20. 30. 40. 50. 60.]
 [ 2. 12. 22. 32. 42. 52. 62.]]


#### 陣列訪問

In [41]:
#一維照列
np1 = np.arange(0,10)
print(np1)
print("np1[0] = %d , np1[5] = %d" % (np1[0],np1[5]))
print("np1[:5] = ",np1[:5])
print("np1[3:7] = ",np1[3:7])
print("np1[6:] = ",np1[6:])
print(np1[1:6:2])
print(np1[1::2])
print(np1[::3])

[0 1 2 3 4 5 6 7 8 9]
np1[0] = 0 , np1[5] = 5
np1[:5] =  [0 1 2 3 4]
np1[3:7] =  [3 4 5 6]
np1[6:] =  [6 7 8 9]
[1 3 5]
[1 3 5 7 9]
[0 3 6 9]


In [42]:
#使用布林遮罩來取值
np3 = np.array([1, 2, 3, 4, 5, 6])
print(np3 > 3)

[False False False  True  True  True]


In [43]:
np3[np3<3]=0
print(np3)

[0 0 3 4 5 6]


#### 改變數組的維度

In [44]:
#使用reshape 函數

#a = np.arange(18)
#print(a)
#print(a.reshape(2,3,3))

a = np.arange(18).reshape(2,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [45]:
#使用ravel函數 ,將數組轉為一維 , return view

print(a.ravel())

#使用 flatten 函數 ,將數組轉為一維, 使用記憶體來保存結果
print(a.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


#### 組合數組

In [46]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
# 純量計算
b = a * 3 
b

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [48]:
# 水平組合 
#使用 hstack()
np.hstack((a, b)) 

#使用 np.concatenate()
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  3,  6],
       [ 3,  4,  5,  9, 12, 15],
       [ 6,  7,  8, 18, 21, 24]])

In [49]:
# 垂直組合
#使用 vstack()
np.vstack((a, b)) 
#使用 np.concatenate()
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [50]:
# 深度組合
# 使用 dstack()
c = np.dstack((a, b))
print(c)
print(c.shape)

[[[ 0  0]
  [ 1  3]
  [ 2  6]]

 [[ 3  9]
  [ 4 12]
  [ 5 15]]

 [[ 6 18]
  [ 7 21]
  [ 8 24]]]
(3, 3, 2)


In [51]:
# 列組合
# 使用 column_stack()
# column_stack((a, b)) == hstack((a, b)) 
c = np.column_stack((a, b))
print(c)
print(c.shape)

[[ 0  1  2  0  3  6]
 [ 3  4  5  9 12 15]
 [ 6  7  8 18 21 24]]
(3, 6)


In [52]:
# 行組合
# 使用 row_stack()
# row_stack((a,b)) == vstack((a, b)) 
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

#### 數組分割

In [53]:
# 分割
a = np.arange(9).reshape(3,3)

print(a)

np.hsplit(a,3)

#np.split(a,3,axis = 1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [54]:

# 重直分割
a = np.arange(9).reshape(3,3)

print(a)

np.vsplit(a,3)

#np.split(a,3,axis = 0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [55]:
# 水平分割
a = np.arange(9).reshape(3,3)
print(a)

np.hsplit(a,3)

#np.split(a,3,axis = 1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [56]:
# 深度分割
a = np.arange(27).reshape(3,3,3)
print(a)

np.dsplit(a,3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

#### 矩陣運算

##### 矩陣加減

* 矩陣加法有交換律,減法沒有交換律
* 矩陣加法有結合律,減法沒有結合律

In [58]:
A = np.array([[12,23,14],[20,29,38],[3,6,10],[15,15,2]])
B = np.array([[13,33,22],[10,19,8],[30,0,20],[0,0,0]])
print(A+B)
print(B+A)
np.array_equal(A+B,B+A)

[[25 56 36]
 [30 48 46]
 [33  6 30]
 [15 15  2]]
[[25 56 36]
 [30 48 46]
 [33  6 30]
 [15 15  2]]


True

In [59]:
A = np.array([[12,23,14],[20,29,38],[3,6,10],[15,15,2]])
B = np.array([[13,33,22],[10,19,8],[30,0,20],[0,0,0]])
print(A-B)
print(B-A)
np.array_equal(A-B,B-A)

[[ -1 -10  -8]
 [ 10  10  30]
 [-27   6 -10]
 [ 15  15   2]]
[[  1  10   8]
 [-10 -10 -30]
 [ 27  -6  10]
 [-15 -15  -2]]


False

In [60]:
A = np.array([[5,3],[0,1]])
B = np.array([[4,-1],[2,3]])
C = np.array([[9,8],[-6,2]])
print((A+B)+C)
print(A+(B+C))

np.array_equal((A+B)+C,A+(B+C))

[[18 10]
 [-4  6]]
[[18 10]
 [-4  6]]


True

In [61]:

np.array_equal((A-B)-C,A-(B-C))

False

##### 矩陣乘法

* 矩陣A為 m x n、矩陣B為 p x q，n 與 p 要相等， A * B 才能進行運算
* .dot() 函數來實現矩陣與矩陣的相乘
* 矩陣相乘具有結合律,分配律

In [63]:
A = np.array([
    [10, -20, 15],
    [0, 15, -5],
    [2, 4, 6]
])
B = np.array([
    [1, 2, -3],
    [4, -5, 6],
    [7, 8, 9]
])

print(A.dot(B))

[[  35  240  -15]
 [  25 -115   45]
 [  60   32   72]]


In [66]:
A = np.array([
    [1, -1],
    [2, 4]
])
B = np.array([
    [3, 1],
    [2, 0]
])
C = np.array([
    [-4, -2],
    [5, -10]
])
D = (A.dot(B)).dot(C)
E = A.dot(B.dot(C))
print(D)
print(E)
print(np.array_equal(D, E))

[[  1 -12]
 [-46 -48]]
[[  1 -12]
 [-46 -48]]
True


In [67]:
A = np.array([
    [1, -1],
    [2, 4]
])
B = np.array([
    [3, 1],
    [2, 0]
])
C = np.array([
    [-4, -2],
    [5, -10]
])

D = A.dot(B + C)
E = A.dot(B) + A.dot(C)
print(D)
print(E)
print(np.array_equal(D, E))

[[ -8   9]
 [ 26 -42]]
[[ -8   9]
 [ 26 -42]]
True


##### 轉置矩陣

In [69]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B = A.T
print(B)

[[1 3 5]
 [2 4 6]]


In [70]:

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

C = (A + B).T
D = A.T + B.T
print(C)
print(D)
print(np.array_equal(C, D))

[[ 8 12 16]
 [10 14 18]]
[[ 8 12 16]
 [10 14 18]]
True


In [71]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B = np.array([
    [1, 0, 2],
    [4, 5, 6]
])
C = (A.dot(B)).T
D = (B.T).dot(A.T)
print(np.array_equal(C, D))

True


##### 反矩陣

* 反矩陣（Inverse）：如果矩陣 M 是一個可逆矩陣（invertible），則矩陣 M 與其反矩陣相乘之後可以得到一個單位矩陣 => 不是每個矩陣都具有反矩陣
* np.linalg.inv() 函數計算反矩陣

In [74]:
A = np.array([
    [4, -7],
    [2, -3]
])
A_inv = np.linalg.inv(A)
print(A_inv)
print(A.dot(A_inv))

[[-1.5  3.5]
 [-1.   2. ]]
[[1. 0.]
 [0. 1.]]


In [75]:
B = np.array([
    [8, 2],
    [12, 3]
])
try:
    B_inv = np.linalg.inv(B)
except np.linalg.LinAlgError:
    print('矩陣 B 是不可逆矩陣')

矩陣 B 是不可逆矩陣
